---
- name: Ensure required package is installed on Debian-based systems
  apt:
    name: "{{ package_name }}"
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Ensure required package is installed on RedHat-based systems
  yum:
    name: "{{ package_name }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  become: true
